---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:

  - name: npm install
    image: node:17-alpine
    commands:
      - npm install

  - name: npm run lint
    image: node:17-alpine
    commands:
      - npm run lint

  - name: npm publish
    image: node:17-alpine
    commands:
      - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> .npmrc
      - echo "email = $NPM_EMAIL" >> ~/.npmrc
      - npm publish
    environment:
      NPM_AUTH_TOKEN:
        from_secret: npm_token
      NPM_EMAIL: tyhou13@gmx.com
    when:
      ref:
        - refs/tags/*

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:

  - name: npm install
    image: node:17-alpine
    commands:
      - npm install

  - name: npm run lint
    image: node:17-alpine
    commands:
      - npm run lint
